### ISSUE TITLE
.DirIcon is missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [imaginaryfilms/Teleprompter-Electron#3]
`.DirIcon` is missing in the AppImage. As a result, software like `appimaged` and AppImageLauncher can't show a proper icon.

![iconmissnig](https://user-images.githubusercontent.com/2480569/59623430-a46cfe00-9123-11e9-8cd1-7347359a5a23.png)

Please put e.g., a 512x512 pixel png as `.DirIcon` in the root of the AppImage.

**Comment by Cuperino** [comment]
Hello @probonopd, thanks for letting us know of this issue. We plan on releasing a final update to Imaginary Teleprompter's 2.x series next month. I'll make sure this bug gets fixed for the next AppImages.

**Comment by Cuperino** [comment]
By using Electron Builder 20.14.7 to generate the distribution packages for version 2.4, this issue is officially solved. I tested on Pop!_OS 19.10 using `AppImageLauncher` 2.1.2 and `Files` 3.34.1-stable.
